### ISSUE TITLE
Old tagged releases removed and overwritten?

### ISSUE THREAD

**Issue by marcovtwout** [codemasher/php-googleauth#5]
@codemasher One of my colleagues noticed some suprises in the git and release history for this package.

It looks a lot like you dropped earlier releases, but worse, removed and reused tagged versions. This could break anyone's project using this package as the code seems to have changed significantly.

Our projects are currently using the following versions which are now missing or overwritten:
- 2.0.1 (removed?) - copy https://api.github.com/repos/chillerlan/php-authenticator/zipball/98841fdc3d2915b292f676e4b5e9fa89aae3511b
- 4.0.0 (removed?) - copy https://api.github.com/repos/chillerlan/php-authenticator/zipball/4959b9e1cd243747f64ba2003cd7da97f4e49c1a
- 4.1.0 (overwritten?) - copy https://api.github.com/repos/chillerlan/php-authenticator/zipball/9cac20a58a906e483ac9ffdc4454f348a1e70a5f

Could you describe what has been done exactly (and why)?

**Comment by codemasher** [comment]
Hey, I'm sorry for the inconvenience! I revisited this repo after a long time not really looking at it and decided it shouldn't be out in the wild in that state. So i rewrote it from ground up and even ported it all the way back to PHP 5.6 and tried to retain the API of the old versions as far as possible so that it shouldn't break things.
So if there's anything I can do to help you minimize the damage done - I'm here!

**Comment by marcovtwout** [comment]
@codemasher Thanks for responding so quickly!

The main problem is that any existing composer usages could break installations because the tagged versions are missing or changed. I think the best course of action is to restore previously existing tags up to version 4.*. That should take care of any existing installations. Is that still possible?

Then, if you want to re-release your new backported versions, there's a few options. You _could_ break semver and simply make those a new minor version, e.g. 4.2. We found at least one unforeseen API change (details later), so perhaps they are not ready to release.

**Comment by codemasher** [comment]
I looked at the usage statistics and at the time of rewriting it was only at ~2000 installations over the course of the 8 years since i created this repo, so i didn't expect much breaking, in fact, I'm actually surprised that it's been used at all despite so many popular options. And as i mentioned before, i don't want the old code out in the wild. What i can do is to push the old branch and leave it untagged if you insist on keeping the old version, however, I'd recommend upgrading.

**Comment by marcovtwout** [comment]
Recommending the upgrade to v5 is fine ofcourse, but note that not everyone will have PHP 8.2 available yet and PHP 8.0 still has official PHP support. Is there any reason people should not be using versions before 5?

I would really recommend restoring previous tags, despite if you want people using them or not.

If anyone needs the old tagged versions, they can still be found on github using the commit hashes by url, e.g.: `https://github.com/chillerlan/php-authenticator/commit/<commit-hash>`.
- Version history with corresponding commit hashes up to 3.0.0: https://web.archive.org/web/20200915112322/https://github.com/chillerlan/php-authenticator/tags
- 4.0.0: https://github.com/chillerlan/php-authenticator/commit/4959b9e1cd243747f64ba2003cd7da97f4e49c1a
- 4.1.0: https://github.com/chillerlan/php-authenticator/commit/9cac20a58a906e483ac9ffdc4454f348a1e70a5f

**Comment by codemasher** [comment]
The thing is: this won't do anything unless someone has specified a fixed version in their composer.json (which they definitely shouldn't). Existing installations of older versions of this library remain unaffected until someone updates the package that contains it, and, which should adapt the changes. The only place where it`s probably messy is in your build pipeline, because the BC breaks may cause the build to yell at you, Re-tagging the old code will cause more issues due to some BC breaks between minor versions, so the best course of action would be for you to adapt the new versions and release new minor versions for your package.

**Comment by codemasher** [comment]
btw do you have details on what is breaking and why you can't update to the current versions?

**Comment by marcovtwout** [comment]
Thanks for restoring the old main branch, that at least takes care of the floating commit history. 

In the new 4.1 there's at least one method missing compared to the old 4.1, message from our CI tests: `Call to undefined method chillerlan\Authenticator\Authenticator::timeslice()`, which was still documented here: https://github.com/chillerlan/php-authenticator/tree/main-old#:~:text=Create%20a%20code%20for%20a%20UNIX%20timestamp
I don't think we're gonna investigate further though and just update to the current versions.

I still think you should restore previous tags as removing, worse, replacing tags, could cause all sorts of problems with installs / build systems and at the very least developers going "what on earth happened here?".

**Comment by codemasher** [comment]
In general, i agree with you. This repo - like most of my other ones - started as a playground to figure out how things work, originally not even intended for public use. At some point however i learned that other people find my code and use it, so some of my repos became more "professional" while others got left behind. As i said before, due to the low number of total installations i decided it was the better course of action to do what i did and i stand by that, and i apologize for any inconvenience caused - it won't happen again :).

As for the `timeslice()` method - it has been moved to [`TOTP::getCounter()`](https://github.com/chillerlan/php-authenticator/blob/9560e553e83ceb1d2cd7ceddd8a72ca2e9c2bcc1/src/Authenticators/TOTP.php#L26-L34) and to access it you need to invoke that class directly (with the same options) rather than the `Authenticator` which acts as a front-end to the several `AuthenticatorInterface`.
